version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      
  pre_build:
    commands:
      - echo "executing pre build"
      - echo "establish connection with ECR"
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c7v2n4l4
  build:
    commands:
      - mvn package
      - echo "Building docker image"
      - docker docker build -t article_service_public .
      - docker tag article_service_public:latest public.ecr.aws/c7v2n4l4/article_service_public:latest
      - docker push public.ecr.aws/c7v2n4l4/article_service_public:latest
  post_build:
    commands:
      - printf '[{"name":"container_name","imageUri":"image_URI"}]' > imagedefinitions.json
      - echo "Application Built successfully"
artifacts:
    files: imagedefinitions.json